### PR TITLE
Deserialize nested errors

### LINKED ISSUE #46: Nested Error's are not deserialized
When I use nested Error's they are serialized, but not deserialized, am I missing something?:

```js
const {serializeError, deserializeError} = require('serialize-error');

class MyError extends Error {    
    constructor(message, innerError) {
        super(message);

        this.innerError = innerError;
    }
}

const error = new MyError('Error message', new Error('inner error'));
const serialized = serializeError(error)
console.log(serialized);
/* outputs:
{
    name: 'Error',
    message: 'Error message',
    stack: '<cut>',
    innerError: {
        name: 'Error',
        message: 'inner error',
        stack: '<cut>'
    }
}
*/
const deserialized = deserializeError(serialized);
console.log(deserialized);
/* outputs:
Error: Error message
    at <cut> {
  innerError: {}
}
*/
```

### PR DESCRIPTION
**Pull request by fregante**
Closes #46 

Includes and is blocked by #68

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -200,6 +200,28 @@ test('should deserialize plain object', t => {
 	t.is(deserialized.code, 'code');
 });
 
+test('should deserialize nested errors', t => {
```
Comment (fregante) [inline test.js:203]: I duplicate this test because the non-enumerable `cause` is treated differently from other props, so this test can work while `cause` fails and viceversa

Comment (fregante) [reply test.js]: I inlined this comment and improved the code

**Comment by sindresorhus** [comment]
Merge conflict
