### PR TITLE
Make serialized error properties enumerable

### LINKED ISSUE #31: v7 doesn't work as described
The breaking change in v7 turned the example from the `README.md` useless:

```
const {serializeError, deserializeError} = require('serialize-error');

const error = new Error('🦄');

console.log(error);
//=> [Error: 🦄]

const serialized = serializeError(error)

console.log(serialized);
//=> {name: 'Error', message: '🦄', stack: 'Error: 🦄\n    at Object.<anonymous> …'}

const deserialized = deserializeError(serialized);
//=> [Error: 🦄]
```

The serialized error looks just like an empty object now, and is missing the `name`, `message`, and `stack` properties on the console. Actually, for me this was the most useful feature, and hence v7 is a huge step into the wrong direction.

I understand that you wanted to change it this way to keep things consistent – however, is there a chance to make this configurable?

### PR DESCRIPTION
**Pull request by Weakky**
## Description

Closes #31

Make serialized error properties enumerable again.

@sindresorhus I made `destroyCircular` accept an object as parameter to avoid having a fourth parameter and let `to_` be optional. Hope you don't mind.

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -10,9 +10,11 @@ function deserializeNonError(t, value) {
...
 test('main', t => {
 	const serialized = serializeError(new Error('foo'));
-	t.true('name' in serialized);
-	t.true('stack' in serialized);
-	t.true('message' in serialized);
+	const properties = Object.keys(serialized);
+
+	t.true(properties.includes('name'));
+	t.true(properties.includes('stack'));
+	t.true(properties.includes('message'));
```
Comment (Weakky) [inline test.js:17]: Makes sure serialized props are enumerable

**Comment by sindresorhus** [comment]
Thanks for the quick fix :)
