### PR TITLE
Remove direct usage of Buffer

### LINKED ISSUE #93: Remove direct usage of Buffer
When using this package in a Next.js application, it seems like Webpack is adding the `buffer` node module so it is available in the browser.

This package only uses the Buffer class to verify if an object is one of such kind, and it doesn't use any other functions, so it can be a good idea to use an alternative that won't include the buffer module in the bundle.

---

To reproduce the issue:

Create a Next.js application from a [template with Webpack's bundle analyzer](https://github.com/vercel/next.js/tree/canary/examples/analyze-bundles)

```bash
# Create app
yarn create next-app --example analyze-bundles analyze-bundles-app

# Navigate to the directory
cd analyze-bundles-app

# Install the module
yarn add serialize-error
```

Update `pages/index.tsx` to use the module

```tsx
import { NextPage } from "next";
import { serializeError } from "serialize-error";
import { useState, useEffect } from "react";

const Index: NextPage<void> = () => {
  const [err, setErr] = useState(null);

  useEffect(() => {
    setErr(serializeError(new Error("This is an error")));
  }, []);

  return (
    <div>
      <h1>Test Page</h1>
      <div>{JSON.stringify(err)}</div>
    </div>
  );
};

export default Index;
```

Make a production build with the analyzer plugin

```bash
yarn analyze
```

When the reports are created, open `.next/analyze/client.html` and see that the buffer module is included in the bundle

bundle-with-buffer

### PR DESCRIPTION
**Pull request by VictorPuga**
Updates the logic to verify if the object is a Buffer when removing circular references, avoiding direct usage of the Buffer class

resolves #93

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -93,8 +93,8 @@ const destroyCircular = ({
 	});
 
 	for (const [key, value] of Object.entries(from)) {
-		// eslint-disable-next-line node/prefer-global/buffer
-		if (typeof Buffer === 'function' && Buffer.isBuffer(value)) {
+		if (value !== null && value.constructor !== null &&
```
Comment (sindresorhus) [inline index.js:96]: I would go with `value && value instanceof Uint8Array && value.constructor.name === 'Buffer'`

Comment (VictorPuga) [reply index.js]: I updated the logic as per your recommendation
