### PR TITLE
Incorporate destroy-circular logic. Fixes #2.

### LINKED ISSUE #2: Does not handle circular references.
If an error contains a circular reference (entirely possible with AssertionErrors `actual`, and `expected`), serialization will fail.

Reference: https://github.com/sindresorhus/ava/pull/187

### PR DESCRIPTION
**Pull request by jamestalmage**
For serialized AssertionErrors, it is possible that the `actual`
and `expected` properties contain circular references, causing
a thrown Error when you serialize the result with JSON.stringify().

This destroys circular references on the copied Object. Replacing
them with a string (`[Circular]`).

Also, `JSON.stringify(function() {})` returns `undefined`, and
will drop any functions that are attached to an object it is serializing.
This mimics the latter behavior, but if a function is passed in as the top
level argument, it returns a string (`[Function: fnName]`). Since
the most common use for this is to transmit thrown values for logging,
it makes sense to provide this helpful String instead of `undefined`.
(All this despite the fact it is a terrible idea to throw a function).

Based on:
  https://github.com/jonpacker/destroy-circular/pull/1

Fixes: #2

### CODE REVIEW

File: test.js [hunk 1]
```diff
@@ -1,10 +1,102 @@
...
+import serialize from './';
 
 test(t => {
-	const x = Object.keys(fn(new Error('foo')));
-	t.true(x.includes('name'));
-	t.true(x.includes('stack'));
-	t.true(x.includes('message'));
+	const serialized = serialize(new Error('foo'));
+	const x = Object.keys(serialized);
+	t.not(x.indexOf('name'), -1);
```
Comment (jamestalmage) [inline test.js]: Looks like I found an AVA regression here.

`x.includes` stopped working for me

**Comment by sindresorhus** [comment]
:+1: Looks good.
